### ISSUE TITLE
in es.py about function np.random.normal

### ISSUE THREAD

**Issue by Ashioto** [mbednarski/Chiron#1]
Hi, i found your code in gym CartPole-v0 web page.
in es.py, i noticed that you use np.random.normal function, in which the second parameter is `Standard deviation (spread or "width") of the distribution` not the variance.
Thus, i think the correct way should be like this:
```python
theta[n,:] = np.random.normal(u, sigma)
```
Then i ran your code and got a significant improvement.
The first ten outputs are like this:
9.0
200.0
110.0
73.0
121.0
163.0
200.0
200.0
200.0
200.0
...(all 200.0)

Thanks for your sharing code~ it's quite inspiring.

**Comment by mbednarski** [comment]
Hi!

Yes, you are perfectly right - thank you! I'm working heavily on my code so fixed and refactored version of this will appear soon.
